Add ability to directly configure the S3 ACL
AssetSync/asset_sync pull request #420
Opened 2021-08-04 01:25 UTC by atyndall

Currently, the only mechanism to control the permissions of objects in S3 is via the `config.fog_public` option, which is somewhat limited.

This PR creates the `AssetSync.config.aws_acl` option, which allows the S3 Access Control List for uploaded objects to be set to specific values.

Depending on the situation, setting these more specific values can be quite useful. For instance, `config.aws_acl = 'bucket-owner-full-control'` is used in some situations to ensure that the file uploaded is accessible by the bucket's owner, which may differ from the uploader.

We need this option as the account we are uploading from is different to that which owns the bucket, so we must ensure these ACL permissions are correctly set.

Setting this config value will override the `AssetSync.config.fog_public` setting if set, as it is more specific.

2021-08-04 02:55 UTC, PikachuEXE requested changes
Please also see what changes are made for `aws_signature_version`
And make the same changes for `aws_acl`

And please also update the README about this new attribute
(I do notice `aws_signature_version` and maybe other attributes are also not mentioned in README)
Setting this new attribute overrides `public` option so I think it's worth being mentioned more explicitly

2021-08-04 02:55 UTC, PikachuEXE commented on lib/asset_sync/config.rb
> +    attr_accessor :aws_access_key_id, :aws_secret_access_key, :aws_session_token, :aws_reduced_redundancy, :aws_iam_roles, :aws_signature_version, :aws_acl
I think it's time to make this one line per attribute 
As it becomes too long to read if not
```suggestion
    attr_accessor :aws_access_key_id
    attr_accessor :aws_secret_access_key
    attr_accessor :aws_session_token
    attr_accessor :aws_reduced_redundancy
    attr_accessor :aws_iam_roles
    attr_accessor :aws_signature_version
    attr_accessor :aws_acl

    # Fog
```
The blank line is intended

2021-08-05 01:59 UTC, atyndall commented
@PikachuEXE I have made the changes requested. Please let me know if there is anything else.

2021-08-05 02:05 UTC, PikachuEXE approved these changes
LGTM
I will add missing stuff if I spot any after merge
Probably will be released this week/today

2021-08-05 02:05 UTC, merged

2021-08-05 02:46 UTC, PikachuEXE commented
Just released in `2.15.0`